import turtle
t = turtle.Turtle()
turtle.title("heart shape")
screen = turtle.Screen()
turtle.color("white")
style = ('Arial',60,'italic')
screen.bgcolor("black")
t.color("red")
t.begin_fill()
t.fillcolor("red")
t.left(140)
t.forward(180)
t.circle(-90,200)
t.setheading(60)
t.circle(-90,200)
t.forward(180)
t.end_fill()
t.hideturtle()
turtle.done()

