import turtle
turtle.bgcolor('black')
wn=turtle.Screen()
t=turtle.Turtle()

move=2
t.speed(50)
for i in range (360):
   
    t.write("INDIA ",'false','center',font=('ALGERIAN',50))
    t.penup()
    t.goto(-200,100)
    t.pendown()
    t.color("orange")
    t.right(move)
    t.forward(100)
    t.penup()
    t.color("white")
    t.pendown()
    t.right(30)
    t.forward(60)
    t.pendown()
    t.color("light green")
    t.left(10)
    t.forward(50)
    t.right(70)
    t.penup()
    t.pendown()
    t.color('light blue')
    t.forward(50)
    t.color('light green')
    t.pu()
    t.pd()
    t.color("light blue")
    t.forward(100)
    t.color('brown')
    t.forward(200)
    t.pu()
    t.pd()
    t.color('light green')
    t.circle(2)
    t.color('light blue')
    t.circle(4)
    t.pu()
    t.fd(20)
    t.pd()
    t.circle(6)
    t.pu()
    t.fd(40)
    t.pd()
    t.circle(8)
    t.pu()
    t.fd(80)
    t.pd()
    t.circle(10)
    t.pu()
    t.fd(120)
    t.pd()
    t.circle(20)
    t.color('yellow')
    t.circle(10)
    t.pu()
    t.pd()
    t.color('white')
    t.forward(150)
    t.color('red')
    t.fd(50)
    t.color ('blue')
    t.begin_fill()
    t.penup()
    t.home()
    move=move+1
t.penup()
t.forward(50)
turtle.done()
